server:
  port: 7003

# Eureka配置
eureka:
  instance:
    hostname: localhost7003  # 服务端实例名字
  client:
    register-with-eureka: false #  表示是否向eureka注册自己
    fetch-registry: false # 如果为false,则表示自己是注册中心
    service-url: #监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
