server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

# Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9527.com  #修改eureka上的默认信息
    prefer-ip-address: true


#info配置
info:
  app.name: kuangshen-springcloud
  company.name: blog

#zuul配置
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*" #不能在使用这个路径访问了,隐藏全部的
  prefix: /kuang  #设置公共前缀

